FROM node:24-slim
COPY server.js .
CMD ["node", "server.js"]

==========================================================

FROM node:24-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "start"]